CREATE TABLE OFFERS (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID BIGINT NOT NULL,
  MERCHANT_ID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRICE DECIMAL NOT NULL,
  CURRENCY_ID VARCHAR(3) NOT NULL,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
  FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANTS(ID),
  FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCIES(ID)
)