CREATE TABLE OFFERS (
  ID UUID NOT NULL PRIMARY KEY,
  PRODUCT_ID UUID NOT NULL,
  MERCHANT_ID UUID NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRICE DECIMAL NOT NULL,
  CURRENCY_ID VARCHAR(3) NOT NULL,
  VALIDITY DATE NOT NULL,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
  FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANTS(ID),
  FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCIES(ID)
)